#!/usr/bin/env python3
"""Generate the RISC-V mnemonic/kind/operand table used by the codec."""

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "spec" / "riscv_opcode_kinds.tsv"
OUTPUT = ROOT / "src" / "fortback_riscv_opcode_table.f90"


def read_rows():
    rows = []
    for line_number, line in enumerate(INPUT.read_text().splitlines(), 1):
        fields = line.split()
        if not fields or fields[0].startswith("#"):
            continue
        if len(fields) != 11 or not fields[1].isdigit() or fields[2] not in {"R", "I", "S"}:
            raise SystemExit(f"{INPUT}:{line_number}: malformed row")
        values = fields[3:]
        if any(not value.isdigit() for value in values):
            raise SystemExit(f"{INPUT}:{line_number}: malformed field metadata")
        metadata = tuple(int(value) for value in values)
        if any(value < 0 or value > 31 for value in metadata) or metadata[7] > 12:
            raise SystemExit(f"{INPUT}:{line_number}: malformed field metadata")
        if fields[2] == "I" and any(value == 0 for value in (metadata[0], metadata[1], metadata[2], metadata[3], metadata[6], metadata[7])):
            raise SystemExit(f"{INPUT}:{line_number}: incomplete I-format field metadata")
        if fields[2] == "S" and any(value == 0 for value in (metadata[2], metadata[3], metadata[4], metadata[5], metadata[7])):
            raise SystemExit(f"{INPUT}:{line_number}: incomplete S-format field metadata")
        if fields[2] == "I" and any(value != 0 for value in (metadata[4], metadata[5])):
            raise SystemExit(f"{INPUT}:{line_number}: I-format rs2 metadata must be zero")
        if fields[2] == "R" and any(value != 0 for value in (metadata[6], metadata[7])):
            raise SystemExit(f"{INPUT}:{line_number}: R-format immediate metadata must be zero")
        rows.append((fields[0], int(fields[1]), fields[2], metadata))
    if [row[1] for row in rows] != list(range(1, len(rows) + 1)):
        raise SystemExit(f"{INPUT}: kinds must be consecutive starting at 1")
    return rows


def render(rows):
    lines = [
        "! Generated by scripts/generate_riscv_opcode_table.py; do not edit.",
        "module fortback_riscv_opcode_table",
        "    use iso_fortran_env, only: int32",
        "    implicit none",
        "    private",
        "",
    ]
    for mnemonic, kind, _, _ in rows:
        lines.append(f"    integer(int32), parameter, public :: riscv_{mnemonic} = {kind}_int32")
    lines += [
        "",
        "    public :: riscv_kind_for_mnemonic",
        "    public :: riscv_mnemonic_for_kind",
        "    public :: riscv_immediate_width_for_mnemonic",
        "    public :: riscv_rd_lsb_for_mnemonic",
        "    public :: riscv_rd_width_for_mnemonic",
        "    public :: riscv_rs1_lsb_for_mnemonic",
        "    public :: riscv_rs1_width_for_mnemonic",
        "    public :: riscv_rs2_lsb_for_mnemonic",
        "    public :: riscv_rs2_width_for_mnemonic",
        "    public :: riscv_immediate_lsb_for_mnemonic",
        "",
        "contains",
        "",
        "    pure integer(int32) function riscv_kind_for_mnemonic(mnemonic)",
        "        character(len=*), intent(in) :: mnemonic",
        "",
        "        riscv_kind_for_mnemonic = 0_int32",
        "        select case (trim(mnemonic))",
    ]
    for mnemonic, kind, _, _ in rows:
        lines.append(f"        case ('{mnemonic}')")
        lines.append(f"            riscv_kind_for_mnemonic = riscv_{mnemonic}")
    lines += [
        "        end select",
        "    end function riscv_kind_for_mnemonic",
        "",
        "    pure function riscv_mnemonic_for_kind(kind) result(mnemonic)",
        "        integer(int32), intent(in) :: kind",
        "        character(len=16) :: mnemonic",
        "",
        "        mnemonic = ''",
        "        select case (kind)",
    ]
    for mnemonic, kind, _, _ in rows:
        lines.append(f"        case (riscv_{mnemonic})")
        lines.append(f"            mnemonic = '{mnemonic}'")
    lines += [
        "        end select",
        "    end function riscv_mnemonic_for_kind",
        "",
        "    pure integer(int32) function riscv_immediate_width_for_mnemonic(mnemonic)",
        "        character(len=*), intent(in) :: mnemonic",
        "",
        "        riscv_immediate_width_for_mnemonic = 0_int32",
        "        select case (trim(mnemonic))",
    ]
    for mnemonic, _, _, metadata in rows:
        immediate_width = metadata[7]
        lines.append(f"        case ('{mnemonic}')")
        lines.append(
            f"            riscv_immediate_width_for_mnemonic = {immediate_width}_int32")
    lines += [
        "        end select",
        "    end function riscv_immediate_width_for_mnemonic",
        "",
    ]
    for field_name, field_index in (("rd_lsb", 0), ("rd_width", 1),
                                    ("rs1_lsb", 2), ("rs1_width", 3),
                                    ("rs2_lsb", 4), ("rs2_width", 5),
                                    ("immediate_lsb", 6)):
        function_name = f"riscv_{field_name}_for_mnemonic"
        lines += [
            f"    pure integer(int32) function {function_name}(mnemonic)",
            "        character(len=*), intent(in) :: mnemonic",
            "",
            f"        {function_name} = 0_int32",
            "        select case (trim(mnemonic))",
        ]
        for mnemonic, _, _, metadata in rows:
            lines.append(f"        case ('{mnemonic}')")
            lines.append(f"            {function_name} = {metadata[field_index]}_int32")
        lines += [
            "        end select",
            f"    end function {function_name}",
            "",
        ]
    lines += [
        "end module fortback_riscv_opcode_table",
        "",
    ]
    return "\n".join(lines)


def main():
    generated = render(read_rows())
    if "--check" in sys.argv:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != generated:
            raise SystemExit(f"{OUTPUT} is stale; run {Path(__file__).name}")
    else:
        OUTPUT.write_text(generated)


if __name__ == "__main__":
    main()
