#!/usr/bin/env python3
"""Generate the fixed RISC-V Linux ecall emission policy."""

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "spec" / "mir_v0_riscv_linux_ecall_policy.tsv"
OUTPUT = ROOT / "src" / "fortback_mir_v0_riscv_linux_ecall_policy.f90"


def read_policy():
    operation = None
    operands = {}
    encodings = []
    for line_number, line in enumerate(INPUT.read_text().splitlines(), 1):
        fields = line.split(maxsplit=2)
        if not fields or fields[0].startswith("#"):
            continue
        if fields[:2] == ["operation", "name"] and len(fields) == 3:
            if operation is not None:
                raise SystemExit(f"{INPUT}:{line_number}: duplicate operation")
            operation = fields[2]
        elif fields[0] == "operand" and len(fields) == 3:
            name, value = fields[1], fields[2]
            if name not in {"rd", "rs1", "imm12"} or not value.isdigit():
                raise SystemExit(f"{INPUT}:{line_number}: malformed operand")
            if name in operands:
                raise SystemExit(f"{INPUT}:{line_number}: duplicate operand")
            operands[name] = int(value)
        elif fields[:2] == ["encoding", "field"] and len(fields) == 3:
            encodings.append(fields[2])
        else:
            raise SystemExit(f"{INPUT}:{line_number}: malformed row")
    if operation is None or not operation.isidentifier():
        raise SystemExit(f"{INPUT}: operation name is required")
    if set(operands) != {"rd", "rs1", "imm12"}:
        raise SystemExit(f"{INPUT}: operands must be rd, rs1, and imm12")
    if len(encodings) != 3:
        raise SystemExit(f"{INPUT}: exactly three encoding fields are required")
    return operation, operands, encodings


def render(operation, operands, encodings):
    encoding = " ".join(encodings)
    lines = [
        "! Generated by scripts/generate_mir_v0_riscv_linux_ecall_policy.py; do not edit.",
        "module fortback_mir_v0_riscv_linux_ecall_policy",
        "    use iso_fortran_env, only: int64",
        "    implicit none",
        "    private",
        "",
        f"    character(len=*), parameter, public :: mir_v0_riscv_linux_ecall_operation = '{operation}'",
        "    integer(int64), parameter, public :: mir_v0_riscv_linux_ecall_operands(3) = &",
        f"        [{operands['rd']}_int64, {operands['rs1']}_int64, {operands['imm12']}_int64]",
        f"    character(len=*), parameter, public :: mir_v0_riscv_linux_ecall_encoding = &",
        f"        '{encoding}'",
        "",
        "    public :: mir_v0_riscv_linux_operation_supported",
        "",
        "contains",
        "",
        "    pure logical function mir_v0_riscv_linux_operation_supported(operation)",
        "        character(len=*), intent(in) :: operation",
        "",
        "        select case (trim(operation))",
        f"        case ('{operation}')",
        "            mir_v0_riscv_linux_operation_supported = .true.",
        "        case default",
        "            mir_v0_riscv_linux_operation_supported = .false.",
        "        end select",
        "    end function mir_v0_riscv_linux_operation_supported",
        "",
        "end module fortback_mir_v0_riscv_linux_ecall_policy",
        "",
    ]
    return "\n".join(lines)


def main():
    generated = render(*read_policy())
    if "--check" in sys.argv:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != generated:
            raise SystemExit(f"{OUTPUT} is stale; run {Path(__file__).name}")
    else:
        OUTPUT.write_text(generated)


if __name__ == "__main__":
    main()
