#!/usr/bin/env python3
"""Generate the fixed MIR-v0 bounded RISC-V Linux bridge policy."""

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "spec" / "mir_v0_riscv_linux_bridge_policy.tsv"
OUTPUT = ROOT / "src" / "fortback_mir_v0_riscv_linux_bridge_policy.f90"


def read_policy():
    policy = {"instruction-count": None, "instructions": [], "result-shapes": [], "source-rules": []}
    shape_names = set()
    for line_number, line in enumerate(INPUT.read_text().splitlines(), 1):
        fields = line.split()
        if not fields or fields[0].startswith("#"):
            continue
        if fields[0] == "instruction-count" and len(fields) == 3 and fields[1] == "value":
            if policy["instruction-count"] is not None:
                raise SystemExit(f"{INPUT}:{line_number}: duplicate instruction count")
            policy["instruction-count"] = int(fields[2])
        elif fields[0] == "instruction" and len(fields) == 4 and fields[1] == "opcode":
            policy["instructions"].append((int(fields[2]), fields[3]))
        elif fields[0] == "result-shape" and len(fields) == 5:
            if fields[1] in shape_names:
                raise SystemExit(f"{INPUT}:{line_number}: duplicate result shape")
            shape_names.add(fields[1])
            policy["result-shapes"].append(tuple(fields[1:]))
        elif fields[0] == "source-rule" and len(fields) == 5 and fields[1] == "function":
            if fields[4] not in shape_names:
                raise SystemExit(f"{INPUT}:{line_number}: unknown result shape")
            policy["source-rules"].append(tuple(fields[2:]))
        else:
            raise SystemExit(f"{INPUT}:{line_number}: malformed row")
    if policy["instruction-count"] != len(policy["instructions"]):
        raise SystemExit(f"{INPUT}: instruction count does not match instruction rows")
    if not policy["result-shapes"]:
        raise SystemExit(f"{INPUT}: at least one result-shape row is required")
    if not policy["source-rules"]:
        raise SystemExit(f"{INPUT}: at least one source-rule row is required")
    return policy


def opcode_constant(name):
    return "mir_v0_opcode_" + name.replace("-", "_")


def render(policy):
    source_rules_by_function = {}
    for function_name, source_rule, shape_name in policy["source-rules"]:
        source_rules_by_function.setdefault(function_name, {}).setdefault(source_rule, []).append(shape_name)

    lines = [
        "! Generated by scripts/generate_mir_v0_riscv_linux_bridge_policy.py; do not edit.",
        "module fortback_mir_v0_riscv_linux_bridge_policy",
        "    use iso_fortran_env, only: int32",
        "    use fortback_mir_v0_bridge_metadata, only: mir_v0_opcode_add, &",
        "        mir_v0_opcode_return, mir_v0_value_kind_integer, mir_v0_value_kind_real",
        "    implicit none",
        "    private",
        "",
        f"    integer(int32), parameter, public :: mir_v0_bridge_policy_instruction_count = {policy['instruction-count']}_int32",
        f"    integer(int32), parameter, public :: mir_v0_bridge_policy_result_shape_count = {len(policy['result-shapes'])}_int32",
        "",
        "    public :: mir_v0_bridge_policy_accepts",
        "    public :: mir_v0_bridge_policy_function_supported",
        "    public :: mir_v0_bridge_policy_opcode_supported",
        "",
        "contains",
        "",
        "    pure logical function mir_v0_bridge_policy_result_shape_matches(shape_name, &",
        "            result_id, result_kind, result_type)",
        "        character(len=*), intent(in) :: shape_name, result_type",
        "        integer(int32), intent(in) :: result_id, result_kind",
        "",
        "        mir_v0_bridge_policy_result_shape_matches = .false.",
        "        select case (trim(shape_name))",
    ]
    for shape_name, result_id, result_kind, result_type in policy["result-shapes"]:
        kind_constant = "mir_v0_value_kind_" + result_kind
        lines += [f"        case ('{shape_name}')", f"            if (result_id /= {result_id}_int32) return", f"            if (result_kind /= {kind_constant}) return", f"            if (trim(result_type) /= '{result_type}') return", "            mir_v0_bridge_policy_result_shape_matches = .true."]
    lines += [
        "        case default",
        "            return",
        "        end select",
        "    end function mir_v0_bridge_policy_result_shape_matches",
        "",
        "    pure logical function mir_v0_bridge_policy_function_supported(function_name)",
        "        character(len=*), intent(in) :: function_name",
        "",
        "        select case (trim(function_name))",
    ]
    for function_name in source_rules_by_function:
        lines += [f"        case ('{function_name}')", "            mir_v0_bridge_policy_function_supported = .true."]
    lines += [
        "        case default",
        "            mir_v0_bridge_policy_function_supported = .false.",
        "        end select",
        "    end function mir_v0_bridge_policy_function_supported",
        "",
        "    pure logical function mir_v0_bridge_policy_opcode_supported(opcode)",
        "        integer(int32), intent(in) :: opcode",
        "",
        "        select case (opcode)",
    ]
    for _, opcode in policy["instructions"]:
        lines += [f"        case ({opcode_constant(opcode)})", "            mir_v0_bridge_policy_opcode_supported = .true."]
    lines += [
        "        case default",
        "            mir_v0_bridge_policy_opcode_supported = .false.",
        "        end select",
        "    end function mir_v0_bridge_policy_opcode_supported",
        "",
        "    pure logical function mir_v0_bridge_policy_accepts(function_name, &",
        "            instruction_index, opcode, result_id, result_kind, result_type, &",
        "            source_rule)",
        "        character(len=*), intent(in) :: function_name, result_type, source_rule",
        "        integer(int32), intent(in) :: instruction_index, opcode, result_id, result_kind",
        "",
        "        mir_v0_bridge_policy_accepts = .false.",
        "        if (instruction_index < 0_int32 .or. instruction_index >= &",
        "            mir_v0_bridge_policy_instruction_count) return",
        "        select case (instruction_index)",
    ]
    for index, opcode in policy["instructions"]:
        lines += [f"        case ({index}_int32)", f"            if (opcode /= {opcode_constant(opcode)}) return"]
    lines += ["        case default", "            return", "        end select", "        select case (trim(function_name))"]
    for function_name, source_rules in source_rules_by_function.items():
        lines += [f"        case ('{function_name}')", "            select case (trim(source_rule))"]
        for source_rule, shape_names in source_rules.items():
            lines += [f"            case ('{source_rule}')"]
            for index, shape_name in enumerate(shape_names):
                keyword = "if" if index == 0 else "else if"
                continuation_indent = "                    " if index == 0 else "                        "
                lines += [f"                {keyword} (mir_v0_bridge_policy_result_shape_matches( &", f"{continuation_indent}'{shape_name}', result_id, result_kind, result_type)) then"]
            lines += ["                else", "                    return", "                end if"]
        lines += ["            case default", "                return", "            end select"]
    lines += ["        case default", "            return", "        end select", "        mir_v0_bridge_policy_accepts = .true.", "    end function mir_v0_bridge_policy_accepts", "", "end module fortback_mir_v0_riscv_linux_bridge_policy", ""]
    return "\n".join(lines)


def main():
    policy = read_policy()
    generated = render(policy)
    if "--check" in sys.argv:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != generated:
            raise SystemExit(f"{OUTPUT} is stale; run {Path(__file__).name}")
    else:
        OUTPUT.write_text(generated)


if __name__ == "__main__":
    main()
