#!/usr/bin/env python3
"""Generate the RISC-V mnemonic/kind/operand table used by the codec."""

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "spec" / "riscv_opcode_kinds.tsv"
OUTPUT = ROOT / "src" / "fortback_riscv_opcode_table.f90"


def read_rows():
    rows = []
    for line_number, line in enumerate(INPUT.read_text().splitlines(), 1):
        fields = line.split()
        if not fields or fields[0].startswith("#"):
            continue
        if len(fields) != 4 or not fields[1].isdigit() or fields[2] not in {"R", "I"}:
            raise SystemExit(f"{INPUT}:{line_number}: malformed row")
        if not fields[3].isdigit() or int(fields[3]) < 0 or int(fields[3]) > 12:
            raise SystemExit(f"{INPUT}:{line_number}: malformed immediate width")
        rows.append((fields[0], int(fields[1]), fields[2], int(fields[3])))
    if [row[1] for row in rows] != list(range(1, len(rows) + 1)):
        raise SystemExit(f"{INPUT}: kinds must be consecutive starting at 1")
    return rows


def render(rows):
    lines = [
        "! Generated by scripts/generate_riscv_opcode_table.py; do not edit.",
        "module fortback_riscv_opcode_table",
        "    use iso_fortran_env, only: int32",
        "    implicit none",
        "    private",
        "",
    ]
    for mnemonic, kind, _, _ in rows:
        lines.append(f"    integer(int32), parameter, public :: riscv_{mnemonic} = {kind}_int32")
    lines += [
        "",
        "    public :: riscv_kind_for_mnemonic",
        "    public :: riscv_mnemonic_for_kind",
        "    public :: riscv_immediate_width_for_mnemonic",
        "",
        "contains",
        "",
        "    pure integer(int32) function riscv_kind_for_mnemonic(mnemonic)",
        "        character(len=*), intent(in) :: mnemonic",
        "",
        "        riscv_kind_for_mnemonic = 0_int32",
        "        select case (trim(mnemonic))",
    ]
    for mnemonic, kind, _, _ in rows:
        lines.append(f"        case ('{mnemonic}')")
        lines.append(f"            riscv_kind_for_mnemonic = riscv_{mnemonic}")
    lines += [
        "        end select",
        "    end function riscv_kind_for_mnemonic",
        "",
        "    pure function riscv_mnemonic_for_kind(kind) result(mnemonic)",
        "        integer(int32), intent(in) :: kind",
        "        character(len=16) :: mnemonic",
        "",
        "        mnemonic = ''",
        "        select case (kind)",
    ]
    for mnemonic, kind, _, _ in rows:
        lines.append(f"        case (riscv_{mnemonic})")
        lines.append(f"            mnemonic = '{mnemonic}'")
    lines += [
        "        end select",
        "    end function riscv_mnemonic_for_kind",
        "",
        "    pure integer(int32) function riscv_immediate_width_for_mnemonic(mnemonic)",
        "        character(len=*), intent(in) :: mnemonic",
        "",
        "        riscv_immediate_width_for_mnemonic = 0_int32",
        "        select case (trim(mnemonic))",
    ]
    for mnemonic, _, _, immediate_width in rows:
        lines.append(f"        case ('{mnemonic}')")
        lines.append(
            f"            riscv_immediate_width_for_mnemonic = {immediate_width}_int32")
    lines += [
        "        end select",
        "    end function riscv_immediate_width_for_mnemonic",
        "",
        "end module fortback_riscv_opcode_table",
        "",
    ]
    return "\n".join(lines)


def main():
    generated = render(read_rows())
    if "--check" in sys.argv:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != generated:
            raise SystemExit(f"{OUTPUT} is stale; run {Path(__file__).name}")
    else:
        OUTPUT.write_text(generated)


if __name__ == "__main__":
    main()
