! Generated by scripts/generate_riscv_opcode_table.py; do not edit.
module fortback_riscv_opcode_table
    use iso_fortran_env, only: int32
    implicit none
    private

    integer(int32), parameter, public :: riscv_add = 1_int32
    integer(int32), parameter, public :: riscv_sub = 2_int32
    integer(int32), parameter, public :: riscv_addi = 3_int32
    integer(int32), parameter, public :: riscv_and = 4_int32
    integer(int32), parameter, public :: riscv_or = 5_int32
    integer(int32), parameter, public :: riscv_xor = 6_int32
    integer(int32), parameter, public :: riscv_sll = 7_int32
    integer(int32), parameter, public :: riscv_ori = 8_int32
    integer(int32), parameter, public :: riscv_andi = 9_int32
    integer(int32), parameter, public :: riscv_sra = 10_int32
    integer(int32), parameter, public :: riscv_slli = 11_int32
    integer(int32), parameter, public :: riscv_srli = 12_int32
    integer(int32), parameter, public :: riscv_srai = 13_int32
    integer(int32), parameter, public :: riscv_slti = 14_int32
    integer(int32), parameter, public :: riscv_sltiu = 15_int32
    integer(int32), parameter, public :: riscv_xori = 16_int32
    integer(int32), parameter, public :: riscv_mul = 17_int32
    integer(int32), parameter, public :: riscv_div = 18_int32
    integer(int32), parameter, public :: riscv_ld = 19_int32
    integer(int32), parameter, public :: riscv_sd = 20_int32
    integer(int32), parameter, public :: riscv_sb = 21_int32

    public :: riscv_kind_for_mnemonic
    public :: riscv_mnemonic_for_kind
    public :: riscv_immediate_width_for_mnemonic
    public :: riscv_rd_lsb_for_mnemonic
    public :: riscv_rd_width_for_mnemonic
    public :: riscv_rs1_lsb_for_mnemonic
    public :: riscv_rs1_width_for_mnemonic
    public :: riscv_rs2_lsb_for_mnemonic
    public :: riscv_rs2_width_for_mnemonic
    public :: riscv_immediate_lsb_for_mnemonic

contains

    pure integer(int32) function riscv_kind_for_mnemonic(mnemonic)
        character(len=*), intent(in) :: mnemonic

        riscv_kind_for_mnemonic = 0_int32
        select case (trim(mnemonic))
        case ('add')
            riscv_kind_for_mnemonic = riscv_add
        case ('sub')
            riscv_kind_for_mnemonic = riscv_sub
        case ('addi')
            riscv_kind_for_mnemonic = riscv_addi
        case ('and')
            riscv_kind_for_mnemonic = riscv_and
        case ('or')
            riscv_kind_for_mnemonic = riscv_or
        case ('xor')
            riscv_kind_for_mnemonic = riscv_xor
        case ('sll')
            riscv_kind_for_mnemonic = riscv_sll
        case ('ori')
            riscv_kind_for_mnemonic = riscv_ori
        case ('andi')
            riscv_kind_for_mnemonic = riscv_andi
        case ('sra')
            riscv_kind_for_mnemonic = riscv_sra
        case ('slli')
            riscv_kind_for_mnemonic = riscv_slli
        case ('srli')
            riscv_kind_for_mnemonic = riscv_srli
        case ('srai')
            riscv_kind_for_mnemonic = riscv_srai
        case ('slti')
            riscv_kind_for_mnemonic = riscv_slti
        case ('sltiu')
            riscv_kind_for_mnemonic = riscv_sltiu
        case ('xori')
            riscv_kind_for_mnemonic = riscv_xori
        case ('mul')
            riscv_kind_for_mnemonic = riscv_mul
        case ('div')
            riscv_kind_for_mnemonic = riscv_div
        case ('ld')
            riscv_kind_for_mnemonic = riscv_ld
        case ('sd')
            riscv_kind_for_mnemonic = riscv_sd
        case ('sb')
            riscv_kind_for_mnemonic = riscv_sb
        end select
    end function riscv_kind_for_mnemonic

    pure function riscv_mnemonic_for_kind(kind) result(mnemonic)
        integer(int32), intent(in) :: kind
        character(len=16) :: mnemonic

        mnemonic = ''
        select case (kind)
        case (riscv_add)
            mnemonic = 'add'
        case (riscv_sub)
            mnemonic = 'sub'
        case (riscv_addi)
            mnemonic = 'addi'
        case (riscv_and)
            mnemonic = 'and'
        case (riscv_or)
            mnemonic = 'or'
        case (riscv_xor)
            mnemonic = 'xor'
        case (riscv_sll)
            mnemonic = 'sll'
        case (riscv_ori)
            mnemonic = 'ori'
        case (riscv_andi)
            mnemonic = 'andi'
        case (riscv_sra)
            mnemonic = 'sra'
        case (riscv_slli)
            mnemonic = 'slli'
        case (riscv_srli)
            mnemonic = 'srli'
        case (riscv_srai)
            mnemonic = 'srai'
        case (riscv_slti)
            mnemonic = 'slti'
        case (riscv_sltiu)
            mnemonic = 'sltiu'
        case (riscv_xori)
            mnemonic = 'xori'
        case (riscv_mul)
            mnemonic = 'mul'
        case (riscv_div)
            mnemonic = 'div'
        case (riscv_ld)
            mnemonic = 'ld'
        case (riscv_sd)
            mnemonic = 'sd'
        case (riscv_sb)
            mnemonic = 'sb'
        end select
    end function riscv_mnemonic_for_kind

    pure integer(int32) function riscv_immediate_width_for_mnemonic(mnemonic)
        character(len=*), intent(in) :: mnemonic

        riscv_immediate_width_for_mnemonic = 0_int32
        select case (trim(mnemonic))
        case ('add')
            riscv_immediate_width_for_mnemonic = 0_int32
        case ('sub')
            riscv_immediate_width_for_mnemonic = 0_int32
        case ('addi')
            riscv_immediate_width_for_mnemonic = 12_int32
        case ('and')
            riscv_immediate_width_for_mnemonic = 0_int32
        case ('or')
            riscv_immediate_width_for_mnemonic = 0_int32
        case ('xor')
            riscv_immediate_width_for_mnemonic = 0_int32
        case ('sll')
            riscv_immediate_width_for_mnemonic = 0_int32
        case ('ori')
            riscv_immediate_width_for_mnemonic = 12_int32
        case ('andi')
            riscv_immediate_width_for_mnemonic = 12_int32
        case ('sra')
            riscv_immediate_width_for_mnemonic = 0_int32
        case ('slli')
            riscv_immediate_width_for_mnemonic = 6_int32
        case ('srli')
            riscv_immediate_width_for_mnemonic = 6_int32
        case ('srai')
            riscv_immediate_width_for_mnemonic = 6_int32
        case ('slti')
            riscv_immediate_width_for_mnemonic = 12_int32
        case ('sltiu')
            riscv_immediate_width_for_mnemonic = 12_int32
        case ('xori')
            riscv_immediate_width_for_mnemonic = 12_int32
        case ('mul')
            riscv_immediate_width_for_mnemonic = 0_int32
        case ('div')
            riscv_immediate_width_for_mnemonic = 0_int32
        case ('ld')
            riscv_immediate_width_for_mnemonic = 12_int32
        case ('sd')
            riscv_immediate_width_for_mnemonic = 12_int32
        case ('sb')
            riscv_immediate_width_for_mnemonic = 12_int32
        end select
    end function riscv_immediate_width_for_mnemonic

    pure integer(int32) function riscv_rd_lsb_for_mnemonic(mnemonic)
        character(len=*), intent(in) :: mnemonic

        riscv_rd_lsb_for_mnemonic = 0_int32
        select case (trim(mnemonic))
        case ('add')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('sub')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('addi')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('and')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('or')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('xor')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('sll')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('ori')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('andi')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('sra')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('slli')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('srli')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('srai')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('slti')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('sltiu')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('xori')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('mul')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('div')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('ld')
            riscv_rd_lsb_for_mnemonic = 7_int32
        case ('sd')
            riscv_rd_lsb_for_mnemonic = 0_int32
        case ('sb')
            riscv_rd_lsb_for_mnemonic = 0_int32
        end select
    end function riscv_rd_lsb_for_mnemonic

    pure integer(int32) function riscv_rd_width_for_mnemonic(mnemonic)
        character(len=*), intent(in) :: mnemonic

        riscv_rd_width_for_mnemonic = 0_int32
        select case (trim(mnemonic))
        case ('add')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('sub')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('addi')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('and')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('or')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('xor')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('sll')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('ori')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('andi')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('sra')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('slli')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('srli')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('srai')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('slti')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('sltiu')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('xori')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('mul')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('div')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('ld')
            riscv_rd_width_for_mnemonic = 5_int32
        case ('sd')
            riscv_rd_width_for_mnemonic = 0_int32
        case ('sb')
            riscv_rd_width_for_mnemonic = 0_int32
        end select
    end function riscv_rd_width_for_mnemonic

    pure integer(int32) function riscv_rs1_lsb_for_mnemonic(mnemonic)
        character(len=*), intent(in) :: mnemonic

        riscv_rs1_lsb_for_mnemonic = 0_int32
        select case (trim(mnemonic))
        case ('add')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('sub')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('addi')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('and')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('or')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('xor')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('sll')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('ori')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('andi')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('sra')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('slli')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('srli')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('srai')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('slti')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('sltiu')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('xori')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('mul')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('div')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('ld')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('sd')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        case ('sb')
            riscv_rs1_lsb_for_mnemonic = 15_int32
        end select
    end function riscv_rs1_lsb_for_mnemonic

    pure integer(int32) function riscv_rs1_width_for_mnemonic(mnemonic)
        character(len=*), intent(in) :: mnemonic

        riscv_rs1_width_for_mnemonic = 0_int32
        select case (trim(mnemonic))
        case ('add')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('sub')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('addi')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('and')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('or')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('xor')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('sll')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('ori')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('andi')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('sra')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('slli')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('srli')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('srai')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('slti')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('sltiu')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('xori')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('mul')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('div')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('ld')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('sd')
            riscv_rs1_width_for_mnemonic = 5_int32
        case ('sb')
            riscv_rs1_width_for_mnemonic = 5_int32
        end select
    end function riscv_rs1_width_for_mnemonic

    pure integer(int32) function riscv_rs2_lsb_for_mnemonic(mnemonic)
        character(len=*), intent(in) :: mnemonic

        riscv_rs2_lsb_for_mnemonic = 0_int32
        select case (trim(mnemonic))
        case ('add')
            riscv_rs2_lsb_for_mnemonic = 20_int32
        case ('sub')
            riscv_rs2_lsb_for_mnemonic = 20_int32
        case ('addi')
            riscv_rs2_lsb_for_mnemonic = 0_int32
        case ('and')
            riscv_rs2_lsb_for_mnemonic = 20_int32
        case ('or')
            riscv_rs2_lsb_for_mnemonic = 20_int32
        case ('xor')
            riscv_rs2_lsb_for_mnemonic = 20_int32
        case ('sll')
            riscv_rs2_lsb_for_mnemonic = 20_int32
        case ('ori')
            riscv_rs2_lsb_for_mnemonic = 0_int32
        case ('andi')
            riscv_rs2_lsb_for_mnemonic = 0_int32
        case ('sra')
            riscv_rs2_lsb_for_mnemonic = 20_int32
        case ('slli')
            riscv_rs2_lsb_for_mnemonic = 0_int32
        case ('srli')
            riscv_rs2_lsb_for_mnemonic = 0_int32
        case ('srai')
            riscv_rs2_lsb_for_mnemonic = 0_int32
        case ('slti')
            riscv_rs2_lsb_for_mnemonic = 0_int32
        case ('sltiu')
            riscv_rs2_lsb_for_mnemonic = 0_int32
        case ('xori')
            riscv_rs2_lsb_for_mnemonic = 0_int32
        case ('mul')
            riscv_rs2_lsb_for_mnemonic = 20_int32
        case ('div')
            riscv_rs2_lsb_for_mnemonic = 20_int32
        case ('ld')
            riscv_rs2_lsb_for_mnemonic = 0_int32
        case ('sd')
            riscv_rs2_lsb_for_mnemonic = 20_int32
        case ('sb')
            riscv_rs2_lsb_for_mnemonic = 20_int32
        end select
    end function riscv_rs2_lsb_for_mnemonic

    pure integer(int32) function riscv_rs2_width_for_mnemonic(mnemonic)
        character(len=*), intent(in) :: mnemonic

        riscv_rs2_width_for_mnemonic = 0_int32
        select case (trim(mnemonic))
        case ('add')
            riscv_rs2_width_for_mnemonic = 5_int32
        case ('sub')
            riscv_rs2_width_for_mnemonic = 5_int32
        case ('addi')
            riscv_rs2_width_for_mnemonic = 0_int32
        case ('and')
            riscv_rs2_width_for_mnemonic = 5_int32
        case ('or')
            riscv_rs2_width_for_mnemonic = 5_int32
        case ('xor')
            riscv_rs2_width_for_mnemonic = 5_int32
        case ('sll')
            riscv_rs2_width_for_mnemonic = 5_int32
        case ('ori')
            riscv_rs2_width_for_mnemonic = 0_int32
        case ('andi')
            riscv_rs2_width_for_mnemonic = 0_int32
        case ('sra')
            riscv_rs2_width_for_mnemonic = 5_int32
        case ('slli')
            riscv_rs2_width_for_mnemonic = 0_int32
        case ('srli')
            riscv_rs2_width_for_mnemonic = 0_int32
        case ('srai')
            riscv_rs2_width_for_mnemonic = 0_int32
        case ('slti')
            riscv_rs2_width_for_mnemonic = 0_int32
        case ('sltiu')
            riscv_rs2_width_for_mnemonic = 0_int32
        case ('xori')
            riscv_rs2_width_for_mnemonic = 0_int32
        case ('mul')
            riscv_rs2_width_for_mnemonic = 5_int32
        case ('div')
            riscv_rs2_width_for_mnemonic = 5_int32
        case ('ld')
            riscv_rs2_width_for_mnemonic = 0_int32
        case ('sd')
            riscv_rs2_width_for_mnemonic = 5_int32
        case ('sb')
            riscv_rs2_width_for_mnemonic = 5_int32
        end select
    end function riscv_rs2_width_for_mnemonic

    pure integer(int32) function riscv_immediate_lsb_for_mnemonic(mnemonic)
        character(len=*), intent(in) :: mnemonic

        riscv_immediate_lsb_for_mnemonic = 0_int32
        select case (trim(mnemonic))
        case ('add')
            riscv_immediate_lsb_for_mnemonic = 0_int32
        case ('sub')
            riscv_immediate_lsb_for_mnemonic = 0_int32
        case ('addi')
            riscv_immediate_lsb_for_mnemonic = 20_int32
        case ('and')
            riscv_immediate_lsb_for_mnemonic = 0_int32
        case ('or')
            riscv_immediate_lsb_for_mnemonic = 0_int32
        case ('xor')
            riscv_immediate_lsb_for_mnemonic = 0_int32
        case ('sll')
            riscv_immediate_lsb_for_mnemonic = 0_int32
        case ('ori')
            riscv_immediate_lsb_for_mnemonic = 20_int32
        case ('andi')
            riscv_immediate_lsb_for_mnemonic = 20_int32
        case ('sra')
            riscv_immediate_lsb_for_mnemonic = 0_int32
        case ('slli')
            riscv_immediate_lsb_for_mnemonic = 20_int32
        case ('srli')
            riscv_immediate_lsb_for_mnemonic = 20_int32
        case ('srai')
            riscv_immediate_lsb_for_mnemonic = 20_int32
        case ('slti')
            riscv_immediate_lsb_for_mnemonic = 20_int32
        case ('sltiu')
            riscv_immediate_lsb_for_mnemonic = 20_int32
        case ('xori')
            riscv_immediate_lsb_for_mnemonic = 20_int32
        case ('mul')
            riscv_immediate_lsb_for_mnemonic = 0_int32
        case ('div')
            riscv_immediate_lsb_for_mnemonic = 0_int32
        case ('ld')
            riscv_immediate_lsb_for_mnemonic = 20_int32
        case ('sd')
            riscv_immediate_lsb_for_mnemonic = 0_int32
        case ('sb')
            riscv_immediate_lsb_for_mnemonic = 0_int32
        end select
    end function riscv_immediate_lsb_for_mnemonic

end module fortback_riscv_opcode_table
