! Generated by scripts/generate_mir_v0_riscv_linux_ecall_policy.py; do not edit.
module fortback_mir_v0_riscv_linux_ecall_policy
    use iso_fortran_env, only: int64
    implicit none
    private

    character(len=*), parameter, public :: mir_v0_riscv_linux_ecall_operation = 'ecall'
    integer(int64), parameter, public :: mir_v0_riscv_linux_ecall_operands(3) = &
        [0_int64, 0_int64, 0_int64]
    character(len=*), parameter, public :: mir_v0_riscv_linux_ecall_encoding = &
        '14..12=0 6..2=0x1C 1..0=3'

    public :: mir_v0_riscv_linux_operation_supported

contains

    pure logical function mir_v0_riscv_linux_operation_supported(operation)
        character(len=*), intent(in) :: operation

        select case (trim(operation))
        case ('ecall')
            mir_v0_riscv_linux_operation_supported = .true.
        case default
            mir_v0_riscv_linux_operation_supported = .false.
        end select
    end function mir_v0_riscv_linux_operation_supported

end module fortback_mir_v0_riscv_linux_ecall_policy
