! Generated by scripts/generate_mir_v0_riscv_linux_bridge_policy.py; do not edit.
module fortback_mir_v0_riscv_linux_bridge_policy
    use iso_fortran_env, only: int32
    use fortback_mir_v0_bridge_metadata, only: mir_v0_opcode_add, &
        mir_v0_opcode_mul, &
        mir_v0_opcode_div, &
        mir_v0_opcode_sub, &
        mir_v0_opcode_store, &
        mir_v0_opcode_return, &
        mir_v0_opcode_const, &
        mir_v0_opcode_load, &
        mir_v0_value_kind_complex, &
        mir_v0_value_kind_integer, mir_v0_value_kind_logical, &
        mir_v0_value_kind_real, mir_v0_value_kind_character
    implicit none
    private

    integer(int32), parameter, public :: mir_v0_bridge_policy_instruction_count = 8_int32
    integer(int32), parameter, public :: mir_v0_bridge_policy_result_shape_count = 11_int32
    character(len=16), parameter, public :: mir_v0_bridge_policy_storage_key = 'x'
    integer(int32), parameter, public :: mir_v0_bridge_policy_storage_offset = 0_int32
    integer(int32), parameter, public :: mir_v0_bridge_policy_frame_size = 16_int32
    integer(int32), parameter, public :: mir_v0_bridge_policy_storage_initialization = 0_int32
    character(len=16), parameter, public :: mir_v0_bridge_policy_load_operation = 'ld'
    character(len=16), parameter, public :: mir_v0_bridge_policy_store_operation = 'sd'

    public :: mir_v0_bridge_policy_accepts
    public :: mir_v0_bridge_policy_function_supported
    public :: mir_v0_bridge_policy_opcode_supported
    public :: mir_v0_bridge_policy_instruction_count_for
    public :: mir_v0_bridge_policy_instruction_count_matches
    public :: mir_v0_bridge_policy_machine_operation_for
    public :: mir_v0_bridge_policy_frame_operation
    public :: mir_v0_bridge_policy_exit_status_operation
    public :: mir_v0_bridge_policy_route_operation_for
    public :: mir_v0_bridge_policy_storage_matches

contains

    pure logical function mir_v0_bridge_policy_storage_matches(storage_present, storage_key)
        logical, intent(in) :: storage_present
        character(len=*), intent(in) :: storage_key

        mir_v0_bridge_policy_storage_matches = .not. storage_present
        if (storage_present) mir_v0_bridge_policy_storage_matches = &
            trim(storage_key) == trim(mir_v0_bridge_policy_storage_key)
    end function mir_v0_bridge_policy_storage_matches

    pure logical function mir_v0_bridge_policy_result_shape_matches(shape_name, &
            result_id, result_kind, result_type)
        character(len=*), intent(in) :: shape_name, result_type
        integer(int32), intent(in) :: result_id, result_kind

        mir_v0_bridge_policy_result_shape_matches = .false.
        select case (trim(shape_name))
        case ('integer')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_integer) return
            if (trim(result_type) /= 'i32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('integer-loaded')
            if (result_id /= 0_int32) return
            if (result_kind /= mir_v0_value_kind_integer) return
            if (trim(result_type) /= 'i32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('integer-expression')
            if (result_id /= 2_int32) return
            if (result_kind /= mir_v0_value_kind_integer) return
            if (trim(result_type) /= 'i32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('integer-literal-left')
            if (result_id /= 0_int32) return
            if (result_kind /= mir_v0_value_kind_integer) return
            if (trim(result_type) /= 'i32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('integer-literal-right')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_integer) return
            if (trim(result_type) /= 'i32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('integer-expression-result')
            if (result_id /= 2_int32) return
            if (result_kind /= mir_v0_value_kind_integer) return
            if (trim(result_type) /= 'i32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('real')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_real) return
            if (trim(result_type) /= 'f32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('double')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_real) return
            if (trim(result_type) /= 'f64') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('complex')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_complex) return
            if (trim(result_type) /= 'c32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('character')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_character) return
            if (trim(result_type) /= 'character') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('logical')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_logical) return
            if (trim(result_type) /= 'logical') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case default
            return
        end select
    end function mir_v0_bridge_policy_result_shape_matches

    pure logical function mir_v0_bridge_policy_function_supported(function_name)
        character(len=*), intent(in) :: function_name

        select case (trim(function_name))
        case ('main')
            mir_v0_bridge_policy_function_supported = .true.
        case ('p')
            mir_v0_bridge_policy_function_supported = .true.
        case default
            mir_v0_bridge_policy_function_supported = .false.
        end select
    end function mir_v0_bridge_policy_function_supported

    pure logical function mir_v0_bridge_policy_opcode_supported(opcode)
        integer(int32), intent(in) :: opcode

        select case (opcode)
        case (mir_v0_opcode_add)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_mul)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_div)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_sub)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_store)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_return)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_const)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_load)
            mir_v0_bridge_policy_opcode_supported = .true.
        case default
            mir_v0_bridge_policy_opcode_supported = .false.
        end select
    end function mir_v0_bridge_policy_opcode_supported

    pure function mir_v0_bridge_policy_machine_operation_for(opcode) result(operation)
        integer(int32), intent(in) :: opcode
        character(len=16) :: operation

        operation = ''
        select case (opcode)
        case (mir_v0_opcode_add)
            operation = 'add'
        case (mir_v0_opcode_mul)
            operation = 'mul'
        case (mir_v0_opcode_div)
            operation = 'div'
        case (mir_v0_opcode_sub)
            operation = 'sub'
        case (mir_v0_opcode_store)
            operation = 'addi'
        case (mir_v0_opcode_return)
            operation = 'return'
        case (mir_v0_opcode_const)
            operation = 'addi'
        case (mir_v0_opcode_load)
            operation = 'addi'
        end select
    end function mir_v0_bridge_policy_machine_operation_for

    pure function mir_v0_bridge_policy_frame_operation() result(operation)
        character(len=16) :: operation
        operation = 'addi'
    end function mir_v0_bridge_policy_frame_operation

    pure function mir_v0_bridge_policy_exit_status_operation() result(operation)
        character(len=16) :: operation
        operation = 'addi'
    end function mir_v0_bridge_policy_exit_status_operation

    pure function mir_v0_bridge_policy_route_operation_for(source_rule, index) result(operation)
        character(len=*), intent(in) :: source_rule
        integer(int32), intent(in) :: index
        character(len=16) :: operation
        operation = ''
        select case (trim(source_rule))
        case ('frontend-ast-v1/storage-sequence')
            select case (index)
            case (0_int32)
                operation = 'addi'
            case (1_int32)
                operation = 'sd'
            case (2_int32)
                operation = 'ld'
            case (3_int32)
                operation = 'addi'
            case (4_int32)
                operation = 'add'
            case (5_int32)
                operation = 'sd'
            case (6_int32)
                operation = 'addi'
            end select
        end select
    end function mir_v0_bridge_policy_route_operation_for

    pure integer(int32) function mir_v0_bridge_policy_instruction_count_for( &
            function_name, source_rule)
        character(len=*), intent(in) :: function_name, source_rule

        mir_v0_bridge_policy_instruction_count_for = 0_int32
        select case (trim(function_name))
        case ('main')
            select case (trim(source_rule))
            case ('frontend-v0/program')
                mir_v0_bridge_policy_instruction_count_for = 2_int32
            case ('frontend-ast-v1/program')
                mir_v0_bridge_policy_instruction_count_for = 2_int32
            case ('frontend-ast-v1/assignment')
                mir_v0_bridge_policy_instruction_count_for = 2_int32
            case ('frontend-ast-v1/expression')
                mir_v0_bridge_policy_instruction_count_for = 3_int32
            case ('frontend-ast-v1/storage-sequence')
                mir_v0_bridge_policy_instruction_count_for = 7_int32
            end select
        case ('p')
            select case (trim(source_rule))
            case ('frontend-ast-v1/program')
                mir_v0_bridge_policy_instruction_count_for = 2_int32
            end select
        end select
    end function mir_v0_bridge_policy_instruction_count_for

    pure logical function mir_v0_bridge_policy_instruction_count_matches( &
            function_name, source_rule, instruction_count)
        character(len=*), intent(in) :: function_name, source_rule
        integer(int32), intent(in) :: instruction_count

        mir_v0_bridge_policy_instruction_count_matches = .false.
        select case (trim(function_name))
        case ('main')
            select case (trim(source_rule))
            case ('frontend-v0/program')
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
            case ('frontend-ast-v1/program')
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
            case ('frontend-ast-v1/assignment')
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 3_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
            case ('frontend-ast-v1/expression')
                if (instruction_count == 3_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 5_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 5_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 5_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 5_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 5_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 3_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 3_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 3_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
            case ('frontend-ast-v1/storage-sequence')
                if (instruction_count == 7_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
            end select
        case ('p')
            select case (trim(source_rule))
            case ('frontend-ast-v1/program')
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
                if (instruction_count == 2_int32) then
                    mir_v0_bridge_policy_instruction_count_matches = .true.
                    return
                end if
            end select
        end select
    end function mir_v0_bridge_policy_instruction_count_matches

    pure logical function mir_v0_bridge_policy_accepts(function_name, &
            instruction_count, instruction_index, opcode, result_id, result_kind, &
            result_type, source_rule, literal_present, literal)
        character(len=*), intent(in) :: function_name, result_type, source_rule
        logical, intent(in) :: literal_present
        integer(int32), intent(in) :: instruction_count, instruction_index, opcode, &
            result_id, result_kind, literal

        mir_v0_bridge_policy_accepts = .false.
        if (instruction_index < 0_int32 .or. instruction_index >= instruction_count) return
        select case (trim(function_name))
        case ('main')
            select case (trim(source_rule))
            case ('frontend-v0/program')
                if (.not. mir_v0_bridge_policy_instruction_count_matches( &
                    function_name, source_rule, instruction_count)) return
                select case (instruction_count)
                case (2_int32)
                    select case (instruction_index)
                    case (0_int32)
                        if (opcode /= mir_v0_opcode_add) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (1_int32)
                        if (opcode /= mir_v0_opcode_return) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case default
                        return
                    end select
                case default
                    return
                end select
                select case (opcode)
                case (mir_v0_opcode_const)
                    if (.not. literal_present) return
                    if (literal < 0_int32 .or. literal > 2047_int32) return
                case default
                    if (literal_present) return
                end select
            case ('frontend-ast-v1/program')
                if (.not. mir_v0_bridge_policy_instruction_count_matches( &
                    function_name, source_rule, instruction_count)) return
                select case (instruction_count)
                case (2_int32)
                    select case (instruction_index)
                    case (0_int32)
                        if (opcode /= mir_v0_opcode_add) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'real', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'double', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'complex', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'character', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'logical', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (1_int32)
                        if (opcode /= mir_v0_opcode_return) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'real', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'double', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'complex', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'character', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'logical', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case default
                        return
                    end select
                case default
                    return
                end select
                select case (opcode)
                case (mir_v0_opcode_const)
                    if (.not. literal_present) return
                    if (literal < 0_int32 .or. literal > 2047_int32) return
                case default
                    if (literal_present) return
                end select
            case ('frontend-ast-v1/assignment')
                if (.not. mir_v0_bridge_policy_instruction_count_matches( &
                    function_name, source_rule, instruction_count)) return
                select case (instruction_count)
                case (2_int32)
                    select case (instruction_index)
                    case (0_int32)
                        if (opcode /= mir_v0_opcode_store) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (1_int32)
                        if (opcode /= mir_v0_opcode_return) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case default
                        return
                    end select
                case (3_int32)
                    select case (instruction_index)
                    case (0_int32)
                        if (opcode /= mir_v0_opcode_const) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (1_int32)
                        if (opcode /= mir_v0_opcode_store) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (2_int32)
                        if (opcode /= mir_v0_opcode_return) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case default
                        return
                    end select
                case default
                    return
                end select
                select case (opcode)
                case (mir_v0_opcode_const)
                    if (.not. literal_present) return
                    if (literal < 0_int32 .or. literal > 2047_int32) return
                case default
                    if (literal_present) return
                end select
            case ('frontend-ast-v1/expression')
                if (.not. mir_v0_bridge_policy_instruction_count_matches( &
                    function_name, source_rule, instruction_count)) return
                select case (instruction_count)
                case (3_int32)
                    select case (instruction_index)
                    case (0_int32)
                        if (opcode /= mir_v0_opcode_add .and. opcode /= mir_v0_opcode_div .and. opcode /= mir_v0_opcode_mul .and. opcode /= mir_v0_opcode_sub) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-expression', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (1_int32)
                        if (opcode /= mir_v0_opcode_store) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (2_int32)
                        if (opcode /= mir_v0_opcode_return) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case default
                        return
                    end select
                case (5_int32)
                    select case (instruction_index)
                    case (0_int32)
                        if (opcode == mir_v0_opcode_const) then
                            if (mir_v0_bridge_policy_result_shape_matches( &
                                'integer-literal-left', result_id, result_kind, result_type)) then
                            else
                                return
                            end if
                        else if (opcode == mir_v0_opcode_load) then
                            if (mir_v0_bridge_policy_result_shape_matches( &
                                'integer-loaded', result_id, result_kind, result_type)) then
                            else
                                return
                            end if
                        else
                            return
                        end if
                    case (1_int32)
                        if (opcode /= mir_v0_opcode_const) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-literal-right', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (2_int32)
                        if (opcode /= mir_v0_opcode_add .and. opcode /= mir_v0_opcode_div .and. opcode /= mir_v0_opcode_mul .and. opcode /= mir_v0_opcode_sub) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-expression-result', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (3_int32)
                        if (opcode /= mir_v0_opcode_store) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-expression-result', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (4_int32)
                        if (opcode /= mir_v0_opcode_return) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-expression-result', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case default
                        return
                    end select
                case default
                    return
                end select
                select case (opcode)
                case (mir_v0_opcode_const)
                    if (.not. literal_present) return
                    if (literal < 0_int32 .or. literal > 2047_int32) return
                case default
                    if (literal_present) return
                end select
            case ('frontend-ast-v1/storage-sequence')
                if (.not. mir_v0_bridge_policy_instruction_count_matches( &
                    function_name, source_rule, instruction_count)) return
                select case (instruction_count)
                case (7_int32)
                    select case (instruction_index)
                    case (0_int32)
                        if (opcode /= mir_v0_opcode_const) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-literal-left', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (1_int32)
                        if (opcode /= mir_v0_opcode_store) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-literal-left', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (2_int32)
                        if (opcode /= mir_v0_opcode_load) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-loaded', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (3_int32)
                        if (opcode /= mir_v0_opcode_const) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-literal-right', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (4_int32)
                        if (opcode /= mir_v0_opcode_add) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-expression', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (5_int32)
                        if (opcode /= mir_v0_opcode_store) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-expression-result', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (6_int32)
                        if (opcode /= mir_v0_opcode_return) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer-expression-result', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case default
                        return
                    end select
                case default
                    return
                end select
                select case (opcode)
                case (mir_v0_opcode_const)
                    if (.not. literal_present) return
                    if (literal < 0_int32 .or. literal > 2047_int32) return
                case default
                    if (literal_present) return
                end select
            case default
                return
            end select
        case ('p')
            select case (trim(source_rule))
            case ('frontend-ast-v1/program')
                if (.not. mir_v0_bridge_policy_instruction_count_matches( &
                    function_name, source_rule, instruction_count)) return
                select case (instruction_count)
                case (2_int32)
                    select case (instruction_index)
                    case (0_int32)
                        if (opcode /= mir_v0_opcode_add) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'real', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'double', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'complex', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'character', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'logical', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case (1_int32)
                        if (opcode /= mir_v0_opcode_return) return
                        if (mir_v0_bridge_policy_result_shape_matches( &
                            'integer', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'real', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'double', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'complex', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'character', result_id, result_kind, result_type)) then
                        else if (mir_v0_bridge_policy_result_shape_matches( &
                                'logical', result_id, result_kind, result_type)) then
                        else
                            return
                        end if
                    case default
                        return
                    end select
                case default
                    return
                end select
                select case (opcode)
                case (mir_v0_opcode_const)
                    if (.not. literal_present) return
                    if (literal < 0_int32 .or. literal > 2047_int32) return
                case default
                    if (literal_present) return
                end select
            case default
                return
            end select
        case default
            return
        end select
        mir_v0_bridge_policy_accepts = .true.
    end function mir_v0_bridge_policy_accepts

end module fortback_mir_v0_riscv_linux_bridge_policy
