! Generated by scripts/generate_mir_v0_riscv_linux_bridge_policy.py; do not edit.
module fortback_mir_v0_riscv_linux_bridge_policy
    use iso_fortran_env, only: int32
    use fortback_mir_v0_bridge_metadata, only: mir_v0_opcode_add, &
        mir_v0_opcode_mul, &
        mir_v0_opcode_div, &
        mir_v0_opcode_sub, &
        mir_v0_opcode_store, &
        mir_v0_opcode_return, &
        mir_v0_value_kind_complex, &
        mir_v0_value_kind_integer, mir_v0_value_kind_logical, &
        mir_v0_value_kind_real, mir_v0_value_kind_character
    implicit none
    private

    integer(int32), parameter, public :: mir_v0_bridge_policy_instruction_count = 6_int32
    integer(int32), parameter, public :: mir_v0_bridge_policy_result_shape_count = 7_int32

    public :: mir_v0_bridge_policy_accepts
    public :: mir_v0_bridge_policy_function_supported
    public :: mir_v0_bridge_policy_opcode_supported
    public :: mir_v0_bridge_policy_instruction_count_for

contains

    pure logical function mir_v0_bridge_policy_result_shape_matches(shape_name, &
            result_id, result_kind, result_type)
        character(len=*), intent(in) :: shape_name, result_type
        integer(int32), intent(in) :: result_id, result_kind

        mir_v0_bridge_policy_result_shape_matches = .false.
        select case (trim(shape_name))
        case ('integer')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_integer) return
            if (trim(result_type) /= 'i32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('integer-expression')
            if (result_id /= 2_int32) return
            if (result_kind /= mir_v0_value_kind_integer) return
            if (trim(result_type) /= 'i32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('real')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_real) return
            if (trim(result_type) /= 'f32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('double')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_real) return
            if (trim(result_type) /= 'f64') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('complex')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_complex) return
            if (trim(result_type) /= 'c32') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('character')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_character) return
            if (trim(result_type) /= 'character') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case ('logical')
            if (result_id /= 1_int32) return
            if (result_kind /= mir_v0_value_kind_logical) return
            if (trim(result_type) /= 'logical') return
            mir_v0_bridge_policy_result_shape_matches = .true.
        case default
            return
        end select
    end function mir_v0_bridge_policy_result_shape_matches

    pure logical function mir_v0_bridge_policy_function_supported(function_name)
        character(len=*), intent(in) :: function_name

        select case (trim(function_name))
        case ('main')
            mir_v0_bridge_policy_function_supported = .true.
        case ('p')
            mir_v0_bridge_policy_function_supported = .true.
        case default
            mir_v0_bridge_policy_function_supported = .false.
        end select
    end function mir_v0_bridge_policy_function_supported

    pure logical function mir_v0_bridge_policy_opcode_supported(opcode)
        integer(int32), intent(in) :: opcode

        select case (opcode)
        case (mir_v0_opcode_add)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_mul)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_div)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_sub)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_store)
            mir_v0_bridge_policy_opcode_supported = .true.
        case (mir_v0_opcode_return)
            mir_v0_bridge_policy_opcode_supported = .true.
        case default
            mir_v0_bridge_policy_opcode_supported = .false.
        end select
    end function mir_v0_bridge_policy_opcode_supported

    pure integer(int32) function mir_v0_bridge_policy_instruction_count_for( &
            function_name, source_rule)
        character(len=*), intent(in) :: function_name, source_rule

        mir_v0_bridge_policy_instruction_count_for = 0_int32
        select case (trim(function_name))
        case ('main')
            select case (trim(source_rule))
            case ('frontend-v0/program')
                mir_v0_bridge_policy_instruction_count_for = 2_int32
            case ('frontend-ast-v1/program')
                mir_v0_bridge_policy_instruction_count_for = 2_int32
            case ('frontend-ast-v1/assignment')
                mir_v0_bridge_policy_instruction_count_for = 2_int32
            case ('frontend-ast-v1/expression')
                mir_v0_bridge_policy_instruction_count_for = 3_int32
            end select
        case ('p')
            select case (trim(source_rule))
            case ('frontend-ast-v1/program')
                mir_v0_bridge_policy_instruction_count_for = 2_int32
            end select
        end select
    end function mir_v0_bridge_policy_instruction_count_for

    pure logical function mir_v0_bridge_policy_accepts(function_name, &
            instruction_index, opcode, result_id, result_kind, result_type, &
            source_rule)
        character(len=*), intent(in) :: function_name, result_type, source_rule
        integer(int32), intent(in) :: instruction_index, opcode, result_id, result_kind

        mir_v0_bridge_policy_accepts = .false.
        if (instruction_index < 0_int32 .or. instruction_index >= &
            mir_v0_bridge_policy_instruction_count) return
        select case (trim(function_name))
        case ('main')
            select case (trim(source_rule))
            case ('frontend-v0/program')
                select case (instruction_index)
                case (0_int32)
                    if (opcode /= mir_v0_opcode_add) return
                    if (mir_v0_bridge_policy_result_shape_matches( &
                        'integer', result_id, result_kind, result_type)) then
                    else
                        return
                    end if
                case (1_int32)
                    if (opcode /= mir_v0_opcode_return) return
                    if (mir_v0_bridge_policy_result_shape_matches( &
                        'integer', result_id, result_kind, result_type)) then
                    else
                        return
                    end if
                case default
                    return
                end select
            case ('frontend-ast-v1/program')
                select case (instruction_index)
                case (0_int32)
                    if (opcode /= mir_v0_opcode_add) return
                    if (mir_v0_bridge_policy_result_shape_matches( &
                        'integer', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'real', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'double', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'complex', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'character', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'logical', result_id, result_kind, result_type)) then
                    else
                        return
                    end if
                case (1_int32)
                    if (opcode /= mir_v0_opcode_return) return
                    if (mir_v0_bridge_policy_result_shape_matches( &
                        'integer', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'real', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'double', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'complex', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'character', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'logical', result_id, result_kind, result_type)) then
                    else
                        return
                    end if
                case default
                    return
                end select
            case ('frontend-ast-v1/assignment')
                select case (instruction_index)
                case (0_int32)
                    if (opcode /= mir_v0_opcode_store) return
                    if (mir_v0_bridge_policy_result_shape_matches( &
                        'integer', result_id, result_kind, result_type)) then
                    else
                        return
                    end if
                case (1_int32)
                    if (opcode /= mir_v0_opcode_return) return
                    if (mir_v0_bridge_policy_result_shape_matches( &
                        'integer', result_id, result_kind, result_type)) then
                    else
                        return
                    end if
                case default
                    return
                end select
            case ('frontend-ast-v1/expression')
                select case (instruction_index)
                case (0_int32)
                    if (opcode /= mir_v0_opcode_add .and. opcode /= mir_v0_opcode_mul .and. opcode /= mir_v0_opcode_div .and. opcode /= mir_v0_opcode_sub) return
                    if (mir_v0_bridge_policy_result_shape_matches( &
                        'integer-expression', result_id, result_kind, result_type)) then
                    else
                        return
                    end if
                case (1_int32)
                    if (opcode /= mir_v0_opcode_store) return
                    if (mir_v0_bridge_policy_result_shape_matches( &
                        'integer', result_id, result_kind, result_type)) then
                    else
                        return
                    end if
                case (2_int32)
                    if (opcode /= mir_v0_opcode_return) return
                    if (mir_v0_bridge_policy_result_shape_matches( &
                        'integer', result_id, result_kind, result_type)) then
                    else
                        return
                    end if
                case default
                    return
                end select
            case default
                return
            end select
        case ('p')
            select case (trim(source_rule))
            case ('frontend-ast-v1/program')
                select case (instruction_index)
                case (0_int32)
                    if (opcode /= mir_v0_opcode_add) return
                    if (mir_v0_bridge_policy_result_shape_matches( &
                        'integer', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'real', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'double', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'complex', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'character', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'logical', result_id, result_kind, result_type)) then
                    else
                        return
                    end if
                case (1_int32)
                    if (opcode /= mir_v0_opcode_return) return
                    if (mir_v0_bridge_policy_result_shape_matches( &
                        'integer', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'real', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'double', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'complex', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'character', result_id, result_kind, result_type)) then
                    else if (mir_v0_bridge_policy_result_shape_matches( &
                            'logical', result_id, result_kind, result_type)) then
                    else
                        return
                    end if
                case default
                    return
                end select
            case default
                return
            end select
        case default
            return
        end select
        mir_v0_bridge_policy_accepts = .true.
    end function mir_v0_bridge_policy_accepts

end module fortback_mir_v0_riscv_linux_bridge_policy
