! Generated by scripts/generate_mir_v0_bridge_metadata.py; do not edit.
module fortback_mir_v0_bridge_metadata
    use iso_fortran_env, only: int32
    implicit none
    private

    integer(int32), parameter, public :: mir_v0_opcode_add = 1_int32
    integer(int32), parameter, public :: mir_v0_opcode_sub = 2_int32
    integer(int32), parameter, public :: mir_v0_opcode_mul = 3_int32
    integer(int32), parameter, public :: mir_v0_opcode_div = 4_int32
    integer(int32), parameter, public :: mir_v0_opcode_load = 5_int32
    integer(int32), parameter, public :: mir_v0_opcode_store = 6_int32
    integer(int32), parameter, public :: mir_v0_opcode_compare = 7_int32
    integer(int32), parameter, public :: mir_v0_opcode_branch = 8_int32
    integer(int32), parameter, public :: mir_v0_opcode_call = 9_int32
    integer(int32), parameter, public :: mir_v0_opcode_return = 10_int32
    integer(int32), parameter, public :: mir_v0_opcode_const = 11_int32
    integer(int32), parameter, public :: mir_v0_opcode_output = 12_int32
    integer(int32), parameter, public :: mir_v0_opcode_pow = 13_int32
    integer(int32), parameter, public :: mir_v0_value_kind_integer = 1_int32
    integer(int32), parameter, public :: mir_v0_value_kind_real = 2_int32
    integer(int32), parameter, public :: mir_v0_value_kind_logical = 3_int32
    integer(int32), parameter, public :: mir_v0_value_kind_address = 4_int32
    integer(int32), parameter, public :: mir_v0_value_kind_complex = 5_int32
    integer(int32), parameter, public :: mir_v0_value_kind_character = 6_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_v0_program = 1_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v1_program = 2_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v1_assignment = 3_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v1_expression = 4_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v2_execution_part = 5_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v1_storage_sequence_5 = 6_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v1_storage_sequence_6 = 7_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v1_storage_sequence_7 = 8_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v1_storage_sequence_8 = 9_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v1_storage_sequence_9 = 10_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v1_storage_sequence_10 = 11_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v2_stop_stmt = 12_int32
    integer(int32), parameter, public :: mir_v0_source_rule_frontend_ast_v2_print_stmt = 13_int32

    public :: mir_v0_opcode_value
    public :: mir_v0_value_kind_value
    public :: mir_v0_source_rule_value

contains

    pure integer(int32) function mir_v0_opcode_value(name)
        character(len=*), intent(in) :: name

        mir_v0_opcode_value = 0_int32
        select case (trim(name))
        case ('add')
            mir_v0_opcode_value = mir_v0_opcode_add
        case ('sub')
            mir_v0_opcode_value = mir_v0_opcode_sub
        case ('mul')
            mir_v0_opcode_value = mir_v0_opcode_mul
        case ('div')
            mir_v0_opcode_value = mir_v0_opcode_div
        case ('load')
            mir_v0_opcode_value = mir_v0_opcode_load
        case ('store')
            mir_v0_opcode_value = mir_v0_opcode_store
        case ('compare')
            mir_v0_opcode_value = mir_v0_opcode_compare
        case ('branch')
            mir_v0_opcode_value = mir_v0_opcode_branch
        case ('call')
            mir_v0_opcode_value = mir_v0_opcode_call
        case ('return')
            mir_v0_opcode_value = mir_v0_opcode_return
        case ('const')
            mir_v0_opcode_value = mir_v0_opcode_const
        case ('output')
            mir_v0_opcode_value = mir_v0_opcode_output
        case ('pow')
            mir_v0_opcode_value = mir_v0_opcode_pow
        end select
    end function mir_v0_opcode_value

    pure integer(int32) function mir_v0_value_kind_value(name)
        character(len=*), intent(in) :: name

        mir_v0_value_kind_value = 0_int32
        select case (trim(name))
        case ('integer')
            mir_v0_value_kind_value = mir_v0_value_kind_integer
        case ('real')
            mir_v0_value_kind_value = mir_v0_value_kind_real
        case ('logical')
            mir_v0_value_kind_value = mir_v0_value_kind_logical
        case ('address')
            mir_v0_value_kind_value = mir_v0_value_kind_address
        case ('complex')
            mir_v0_value_kind_value = mir_v0_value_kind_complex
        case ('character')
            mir_v0_value_kind_value = mir_v0_value_kind_character
        end select
    end function mir_v0_value_kind_value

    pure integer(int32) function mir_v0_source_rule_value(name)
        character(len=*), intent(in) :: name

        mir_v0_source_rule_value = 0_int32
        select case (trim(name))
        case ('frontend-v0/program')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_v0_program
        case ('frontend-ast-v1/program')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v1_program
        case ('frontend-ast-v1/assignment')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v1_assignment
        case ('frontend-ast-v1/expression')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v1_expression
        case ('frontend-ast-v2/execution-part')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v2_execution_part
        case ('frontend-ast-v1/storage-sequence-5')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v1_storage_sequence_5
        case ('frontend-ast-v1/storage-sequence-6')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v1_storage_sequence_6
        case ('frontend-ast-v1/storage-sequence-7')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v1_storage_sequence_7
        case ('frontend-ast-v1/storage-sequence-8')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v1_storage_sequence_8
        case ('frontend-ast-v1/storage-sequence-9')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v1_storage_sequence_9
        case ('frontend-ast-v1/storage-sequence-10')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v1_storage_sequence_10
        case ('frontend-ast-v2/stop-stmt')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v2_stop_stmt
        case ('frontend-ast-v2/print-stmt')
            mir_v0_source_rule_value = mir_v0_source_rule_frontend_ast_v2_print_stmt
        end select
    end function mir_v0_source_rule_value

end module fortback_mir_v0_bridge_metadata
